# Form implementation generated from reading ui file 'consulta.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(919, 426)
        self.tableView = QtWidgets.QTableView(parent=Dialog)
        self.tableView.setGeometry(QtCore.QRect(20, 110, 841, 231))
        self.tableView.setObjectName("tableView")
        self.textEdit_Nombre_1 = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit_Nombre_1.setGeometry(QtCore.QRect(80, 20, 231, 31))
        self.textEdit_Nombre_1.setObjectName("textEdit_Nombre_1")
        self.fecha_Actual = QtWidgets.QLabel(parent=Dialog)
        self.fecha_Actual.setGeometry(QtCore.QRect(30, 70, 49, 16))
        self.fecha_Actual.setObjectName("fecha_Actual")
        self.nombre_1 = QtWidgets.QLabel(parent=Dialog)
        self.nombre_1.setGeometry(QtCore.QRect(20, 30, 49, 16))
        self.nombre_1.setObjectName("nombre_1")
        self.buscar_1 = QtWidgets.QPushButton(parent=Dialog)
        self.buscar_1.setGeometry(QtCore.QRect(480, 70, 75, 24))
        self.buscar_1.setObjectName("buscar_1")
        self.textEdit_Apellido = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit_Apellido.setGeometry(QtCore.QRect(380, 20, 241, 31))
        self.textEdit_Apellido.setObjectName("textEdit_Apellido")
        self.apellido = QtWidgets.QLabel(parent=Dialog)
        self.apellido.setGeometry(QtCore.QRect(320, 30, 61, 16))
        self.apellido.setObjectName("apellido")
        self.Fecha_Actual = QtWidgets.QDateEdit(parent=Dialog)
        self.Fecha_Actual.setGeometry(QtCore.QRect(80, 70, 113, 24))
        self.Fecha_Actual.setObjectName("Fecha_Actual")
        self.Fecha_document = QtWidgets.QDateEdit(parent=Dialog)
        self.Fecha_document.setGeometry(QtCore.QRect(340, 70, 113, 24))
        self.Fecha_document.setObjectName("Fecha_document")
        self.fecha_documento = QtWidgets.QLabel(parent=Dialog)
        self.fecha_documento.setGeometry(QtCore.QRect(210, 70, 121, 16))
        self.fecha_documento.setObjectName("fecha_documento")
        self.Tipo_de_trabajo = QtWidgets.QLabel(parent=Dialog)
        self.Tipo_de_trabajo.setGeometry(QtCore.QRect(580, 70, 101, 16))
        self.Tipo_de_trabajo.setObjectName("Tipo_de_trabajo")
        self.Tipo_de_trabajo_2 = QtWidgets.QComboBox(parent=Dialog)
        self.Tipo_de_trabajo_2.setGeometry(QtCore.QRect(690, 70, 91, 24))
        self.Tipo_de_trabajo_2.setObjectName("Tipo_de_trabajo_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.fecha_Actual.setText(_translate("Dialog", "FECHA"))
        self.nombre_1.setText(_translate("Dialog", "NOMBRE"))
        self.buscar_1.setText(_translate("Dialog", "BUSCAR"))
        self.apellido.setText(_translate("Dialog", "APELLIDO"))
        self.fecha_documento.setText(_translate("Dialog", "FECHA DOCUMENTO"))
        self.Tipo_de_trabajo.setText(_translate("Dialog", "TIPO DE TRABAJO"))
